# Generated by Django 6.0.1 on 2026-01-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='gmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
