# Generated by Django 6.0.1 on 2026-01-21 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geeksmodel',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelTable(
            name='geeksmodel',
            table='geeks_table',
        ),
    ]
